import { chromium } from '/opt/homebrew/lib/node_modules/@playwright/test/index.mjs';
const ext = process.argv[2], out = process.argv[3];
const ctx = await chromium.launchPersistentContext('', { channel: 'chromium', headless: true, executablePath: process.env.CHROME_BIN,
  args: [`--disable-extensions-except=${ext}`, `--load-extension=${ext}`] });
let [sw] = ctx.serviceWorkers(); if (!sw) sw = await ctx.waitForEvent('serviceworker');
const id = sw.url().split('/')[2]; console.log('extension id:', id);
const page = await ctx.newPage(); await page.goto('http://127.0.0.1:8765/index.html');
await page.waitForFunction(() => document.documentElement.dataset.prismProbe === 'loaded');
console.log('content script injected: yes');
await page.keyboard.down('Alt'); await page.mouse.move(60, 60); await page.mouse.down();
await page.mouse.move(300, 200, { steps: 5 }); await page.mouse.up(); await page.keyboard.up('Alt');
await page.waitForTimeout(800);
console.log('gesture log:', await page.evaluate(() => document.documentElement.dataset.probeLog));
await page.screenshot({ path: `${out}/page.png` });
const popup = await ctx.newPage(); await popup.goto(`chrome-extension://${id}/popup.html`);
await popup.click('#b'); await popup.waitForSelector('#out:has-text("reply")');
console.log('popup:', await popup.textContent('#out')); await popup.screenshot({ path: `${out}/popup.png` });
const panel = await ctx.newPage(); await panel.goto(`chrome-extension://${id}/panel.html`);
console.log('side panel page renders:', await panel.title() !== undefined);
await ctx.close();
